name: Version Bump

on:
    push:
        branches:
            - 'master'

jobs:
    bump:
        name: Run Version Bump
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            # git checkout project
            - name: Checkout repository
              uses: actions/checkout@v2

            # setup node to be used
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            # setup git
            - name: Setup GIT
              run: |
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
                  git config user.name "$GITHUB_ACTOR"

            # bump major version if the commit message has keys `breaking-change` or `major`
            - name: Major Bump
              env:
                  GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET_KEY }}
              if: (contains(github.event.head_commit.message, 'breaking-change') || contains(github.event.head_commit.message, 'major')) == true
              run: npm version major

            # bump minor version if the commit message has keys `feature` or `minor`
            - name: Minor Bump
              env:
                  GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET_KEY }}
              if: (contains(github.event.head_commit.message, 'feature') || contains(github.event.head_commit.message, 'minor')) == true
              run: npm version minor

            # bump major version if the commit message has keys `hotfix`, `fix` or `patch`
            - name: Patch Bump
              env:
                  GITHUB_TOKEN: ${{ secrets.COMMIT_SECRET_KEY }}
              if: (contains(github.event.head_commit.message, 'hotfix') || contains(github.event.head_commit.message, 'fix') || contains(github.event.head_commit.message, 'patch')) == true
              run: npm version patch

            # Push new version tag, this is required for the next step to generate changelog based on this tagname
            - name: Push tags
              run: git push --tags

            # this step generates changelog and writes to file `output`
            - name: Generate Changelog
              uses: heinrichreimer/github-changelog-generator-action@v2.1.1
              with:
                  token: ${{ secrets.COMMIT_SECRET_KEY }}
                  output: 'CHANGELOG.md'
                  issues: 'true'
                  issuesWoLabels: 'true'
                  pullRequests: 'true'
                  prWoLabels: 'true'
                  simpleList: 'true'
                  author: 'true'

            # Amend the changelog file in the last commit and push to git
            - name: Push commit to git
              run: |
                  git add .
                  git commit --amend --no-edit
                  git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
                  git push --tags "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"
